# action.yml
name: 'GSheets-to-CSV Action'
description: 'Read google sheets into CSV files'
inputs:
  sheets:
    description: 'List of sheets as a JSON string [{id, title, range}] '
    required: true
    default: '[]'
  tempdir:
    description: 'Target directory for CSV files'
    required: false
    default: ${{ env.GITHUB_WORKSPACE }}
  creds:
    description: 'Service account credentials (JSON)'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'

