# action.yml
name: 'GSheets-to-CSV Action'
description: 'Read google sheets into CSV files'
inputs:
  sheets:
    description: 'List of sheets as a JSON string [{id, title, range}] '
    required: true
    default: '[{'id':'1ulqohI6YLYFsz3wm8f5j6BS_JVelu2Ea8SXXa-wwkhQ','title':'Responses','range':'A:I'},{'id':'1ulqohI6YLYFsz3wm8f5j6BS_JVelu2Ea8SXXa-wwkhQ','title':'Polls','range':'A:M'}]'
  tempdir:
    description: 'Target directory for CSV files'
    required: false
    default: ${{ github.workflow }}
  creds:
    description: 'Service account credentials (JSON)'
    required: true
    # is this my GCP creds that I just put in secrets? Or dolt?
    default: ${{ secrets.GSHEET_CREDENTIALS }}
  output_json:
    description: 'Output is space separated (default) or json encoded array of file names'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'

