# action.yml
name: 'GSheets-to-CSV Action'
description: 'Read google sheets into CSV files'
inputs:
  sheets:
    description: 'List of sheets as a JSON string [{id, title, range}] '
    required: true
    default: '[]'
  tempdir:
    description: 'Target directory for CSV files'
    required: false
    default: ${{ github.workflow }}
  creds:
    description: 'Service account credentials (JSON)'
    required: true
    default: ''
  output_json:
    description: 'Output is space separated (default) or json encoded array of file names'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'

