name: Test

on:
  push:
env:
  id: '1ZbkUf1tAzt_Lhh1G8ezDgyU1AdUnm26xzPYLtdtWsI8'
  name: 'temp'
  range: 'A1:I8'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull GSheet data
        id: 'sheet_to_csv'
        uses: ./
        with:
          creds: ${{ secrets.GSHEET_CREDENTIALS }}
          sheets: |
            [
              { "id": "${{ env.id }}", "range": "${{ env.range }}", "title": "${{ env.name }}" },
              { "id": "${{ env.id }}" }
            ]
      - name: Print csv
        id: "print_csv"
        run: |
          linecounts=()
          echo "$FILES" | jq -c '.[]' | while read i; do
              eval file=$i
              newline="$(wc -l $file | awk '{print $1}')"
              echo "$newline"
              linecounts["${#linecounts[@]}"]="${newline}"
              scho "$(wc -l $file)"
          done

          echo $linecounts
          if [ "${linecounts[0]}" != '12' ]; then
              echo "First csv not 12 lines: ${linecounts[1]}"
              exit 1
          elif [ "${linecounts[1]}" != '13500' ]; then
              echo "Second csv not 13500 lines: ${linecounts[2]}"
             exit 1
          fi
        env:
          FILES: ${{ steps.sheet_to_csv.outputs.results }}
