name: Test

on:
  push:
env:
  #sheets:
  id: '1ZbkUf1tAzt_Lhh1G8ezDgyU1AdUnm26xzPYLtdtWsI8'
  name: 'temp'
  range: 'A1:I8'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: PWD
        run: echo "$(pwd)"
      - name: Pull GSheet data
        id: 'sheet_to_csv'
        uses: ./
        with:
          creds: ${{ secrets.GSHEET_CREDENTIALS }}
          sheets: |
            [
              { "id": "${{ env.id }}", "range": "${{ env.range }}", "title": "${{ env.name }}" }
            ]
      - name: Print csv
        id: "print_csv"
        run: |
          echo "$FILES" | jq -c '.[]' | while read i; do
              eval file=$i
              echo "$(wc -l $file)"
          done
        env:
          FILES: ${{ steps.sheet_to_csv.outputs.results }}
